-- BrewMasters Supply Data Analysis Queries

-- Total Sales by Store
-- Query to find the total sales amount for each store.
SELECT st.store_name, SUM(s.total_price) AS total_sales
FROM sales AS s
JOIN stores AS st
ON s.store_id = st.store_id
GROUP BY st.store_name
ORDER BY total_sales DESC;

-- Top 5 Best-Selling Products for Each Store
WITH ranked_products AS(
    SELECT 
        store_name,
        product_name,
        RANK() OVER(PARTITION BY store_name ORDER BY total_products_sold DESC)
    FROM (
        SELECT 
            p.product_name,
            p.category, 
            st.store_name,
            SUM(s.quantity) AS total_products_sold
        FROM sales AS s
        JOIN products AS p
        ON s.product_id = p.product_id
        JOIN stores AS st
        ON s.store_id = st.store_id
        GROUP BY 
            p.product_name, 
            p.category,
            st.store_id) AS products_by_store
)
SELECT *
FROM ranked_products
WHERE rank <= 5;

-- Count of customers grouped by state.
SELECT 
    state, 
    customer_type, 
    COUNT(*)::INTEGER AS total_customers
FROM customers
GROUP BY state, customer_type
ORDER BY state, customer_type;

-- Calculate monthly revenue trend including total sales each month, the delta between months and the cumulative sales by month for each year.
WITH monthly_sales AS (
    SELECT 
        month,
        year,
        SUM(revenue) AS monthly_revenue
    FROM (
        SELECT 
            EXTRACT(MONTH from sale_date) AS month, 
            EXTRACT(YEAR FROM sale_date) AS year,
            total_price AS revenue
        FROM sales) monthly_sales
    GROUP BY month, year
    ORDER BY year, month
)
SELECT 
    month,
    year,
    monthly_revenue AS current_month_rev,
    LAG(monthly_revenue) OVER (ORDER BY year, month) AS previous_month_rev,
    monthly_revenue - LAG(monthly_revenue) OVER (ORDER BY year, month) AS monthly_change_rev,
    SUM(monthly_revenue) OVER (PARTITION BY year ORDER BY year, month) AS cum_annual_sales
FROM monthly_sales;

-- List of marketing campaigns that were active during the height of COVID (Mar 2020 = Jan 2021).
SELECT *
FROM marketing_campaigns
WHERE start_date BETWEEN '2020-03-01' AND '2021-04-01';

-- Campaign budget vs actuals
SELECT 
    c.*, 
    total_marketing_spend.total_expenses,
    c.budget - total_marketing_spend.total_expenses AS budget_diff
FROM marketing_campaigns AS c
LEFT JOIN (
    SELECT 
        campaign_id,
        SUM(amount) AS total_expenses
    FROM marketing_spend
    GROUP BY campaign_id) AS total_marketing_spend
ON c.campaign_id = total_marketing_spend.campaign_id;

-- All-time Sales Performance by Employee
SELECT 
    e.first_name || ' ' || e.last_name AS employee_name,
    e.position,
    st.store_name,
    SUM(s.total_price) AS total_sales
FROM sales AS s
LEFT JOIN employees AS e
ON s.sales_associate_id = e.employee_id
LEFT JOIN stores AS st
ON e.store_id = st.store_id
GROUP BY employee_name, e.position, st.store_name;

-- Total and Average Revenue generated by each position
SELECT 
    e.position,
    COUNT(*) AS total_transactions,
    ROUND(AVG(s.total_price), 2) AS avg_sales,
    SUM(s.total_price) AS total_sales,
    EXTRACT(year from s.sale_date) AS year
FROM sales AS s
LEFT JOIN employees AS e
ON s.sales_associate_id = e.employee_id
GROUP BY e.position, year
ORDER BY year, e.position;

-- Customer Acquisition by Channel
SELECT COUNT(DISTINCT customer_id), channel
FROM sales
GROUP BY channel;

-- Query to analyze total sales by product category, total units by product, along with average revenue per product.
SELECT 
    SUM(s.total_price) AS total_sales,
    SUM(s.quantity) AS total_units_sold,
    AVG(s.total_price) AS avg_product_revenue,
    p.product_name,
    p.category
FROM sales AS s
JOIN products AS p
ON s.product_id = p.product_id
GROUP BY p.category, p.product_name
ORDER BY p.category ASC, total_sales DESC;

-- Customer Lifetime Value (CLV)
-- Query to calculate the total sales revenue generated by each customer and their total number of transactions.
SELECT 
    customer_id,
    COUNT(*) AS total_transactions,
    SUM(total_price) AS total_customer_rev
FROM sales
GROUP BY customer_id
ORDER BY total_customer_rev DESC;